name: LXD Connect Containers

on:
  push:
    branches:
      - main

jobs:
  connect-containers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Install cowsay
      run: |
        sudo apt-get update
        sudo apt-get install -y cowsay
    - name: Ensure Apache2 is running in LXD container
      run: |
            lxc exec application-web -- systemctl is-active apache2 || lxc exec application-web -- systemctl start apache2
    - name: connect-containers
      run: |
        # ip containers lxc list 
        CONTAINER_1_IP=10.42.42.98
        CONTAINER_2_IP=10.42.42.190
        CONTAINER_3_IP=10.42.42.51
        # iptables-L-n-v 
        CONTAINER_1_PORT=80
        CONTAINER_2_PORT=8080
        CONTAINER_3_PORT=3306

        # - name: Configure iptables
        # run: |
        #sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
        #sudo iptables -A INPUT -p udp --dport 53 -j ACCEPT
        #sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT
        
        # cowsay
        cowsay "Cowsay is installed it works!!"

        # webpage
        curl -s "http://katarzyna-da-silva-server.eddi.cloud"
